server.port: 9296

spring:
  application:
    name: CONFIG-SERVICE
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    config:
      server:
        git:
          uri: https://github.com/haalcala/test_microservices_java_springboot2_user_department_full/tree/master/config-server-config
#          clone-on-start: true



